
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = "LOGIN_FAIL"


// Setup company
export const CREATE_COMPANY='CREATE_COMPANY'
export const UPDATE_COMPANY="UPDATE_COMPANY"
export const GET_DETAILS_COMPANY="GET_DETAILS_COMPANY"



// USERS
export const CREATE_USER="CREATE_USER"
export const UPDATE_USER="CREATE_USER"
export const GET_DETAILS_USER="CREATE_USER"
export const GET_ALL_USER="CREATE_USER"

// CLIENT
export const CREATE_CLIENT="CREATE_CLIENT"
export const UPDATE_CLIENT="UPDATE_CLIENT"
export const GET_DETAILS_CLIENT="GET_DETAILS_CLIENT"
export const GET_ALL_CLIENT="GET_ALL_CLIENT"

// Tva
export const CREATE_TVA="CREATE_TVA"
export const UPDATE_TVA="CREATE_TVA"
export const GET_DETAILS_TVA="CREATE_TVA"
export const GET_ALL_TVA="CREATE_TVA"

// PROVIDER
export const CREATE_PROVIDER="CREATE_PROVIDER"
export const UPDATE_PROVIDER="CREATE_PROVIDER"
export const GET_DETAILS_PROVIDER="CREATE_PROVIDER"
export const GET_ALL_PROVIDER="CREATE_PROVIDER"


// permession

// export const GET_ALL_PERMISSION="CREATE_PERMISSION"


// PRODUCT
export const CREATE_PRODUCT="CREATE_PRODUCT"
export const UPDATE_PRODUCT="CREATE_PRODUCT"
export const GET_DETAILS_PRODUCT="CREATE_PRODUCT"
export const GET_ALL_PRODUCT="CREATE_PRODUCT"
export const GET_FULL_DETAILS_PRODUCT="GET_FULL_DETAILS_PRODUCT"


// CATEGORY
export const CREATE_CATEGORY="CREATE_CATEGORY"
export const UPDATE_CATEGORY="CREATE_CATEGORY"
export const GET_DETAILS_CATEGORY="CREATE_CATEGORY"
export const GET_ALL_CATEGORY="CREATE_CATEGORY"

// WAREHOUSE
export const CREATE_WAREHOUSE="CREATE_WAREHOUSE"
export const UPDATE_WAREHOUSE="CREATE_WAREHOUSE"
export const GET_DETAILS_WAREHOUSE="CREATE_WAREHOUSE"
export const GET_ALL_WAREHOUSE="CREATE_WAREHOUSE"


// ACTIVITY
export const GET_DETAILS_ACTIVITY="CREATE_ACTIVITY"
export const GET_ALL_ACTIVITY="CREATE_ACTIVITY"


// UNITES

export const GET_ALL_UNITS="CREATE_UNITS"


// Order
export const GET_DETAILS_ORDER="CREATE_ORDER"
export const GET_ALL_ORDER="CREATE_ORDER"
export const SET_ORDERID="SET_ORDERID"
export const GET_ORDER_BY_ID="GET_ORDER_BY_ID"
export const EMPTY_STATE = "EMPTY_STATE"
export const CODABARS_IMAGES = "CODABARS_IMAGES"
export const EMPTY_ARRAY_PAYMENT = "EMPTY_ARRAY_PAYMENT"


// FINALPRODUCT
export const SEARCH_FINALPRODUCT="SEARCH_FINALPRODUCT"
export const GET_FINALPRODUCT="GET_FINALPRODUCT"

// sell Order
export const SEARCH_SELLORDER="SEARCH_SELLORDER"
export const GET_SELLORDER="GET_SELLORDER"
export const SET_SELLORDERID="SET_SELLORDERID"
export const GET_PIECES="GET_PIECES"
export const HOME_STATISTIC="HOME_STATISTIC"
export const EMPTY_STATE_SELLORDER = "EMPTY_STATE_SELLORDER"
export const ELEMENTS_SELLORDER="ELEMENTS_SELLORDER"
export const SET_CODABAR="SET_CODABAR"
export const SET_PRODUCTION_BARCODES= "SET_PRODUCTION_BARCODES"
export const GET_NOTDELIVERED_PRODUCTION= "GET_NOTDELIVERED_PRODUCTION"

export const EMPTY_STATE_INTERNALORDER= "EMPTY_STATE_INTERNALORDER"


//delivery

export const SEARCH_DELIVERY="SEARCH_DELIVERY"
export const GET_DELIVERY="GET_DELIVERY"

//internal order
export const SEARCH_INTERNALORDER="SEARCH_INTERNALORDER"
export const GET_INTERNALORDER="GET_INTERNALORDER"

export const ACTIVITYE_STATISTIC="ACTIVITYE_STATISTIC"


//payment
export const GET_ALL_PAYMENT_BY_ORDERID = "GET_ALL_PAYMENT_BY_ORDERID"
export const GET_ALL_PAYMENT_SELLORDER = "GET_ALL_PAYMENT_SELLORDER"
export const GET_ALL_PAYMENT_ORDER = "GET_ALL_PAYMENT_ORDER"


//DEVIS
export const SEARCH_DEVIS = "SEARCH_DEVIS"
export const SET_DEVISID = "SET_DEVISID"
export const GET_DEVIS = "GET_DEVIS"

export const SEARCH_MAINTENANCE = "SEARCH_MAINTENANCE"
export const SET_MAINTENANCE_ID = "SET_MAINTENANCE_ID"
export const GET_MAINTENANCE = "GET_MAINTENANCE"
export const SEARCH_PRODUCT_FOR_MAINTENANCE = "SEARCH_PRODUCT_FOR_MAINTENANCE"
export const GET_MAINTENANCE_FILE = "GET_MAINTENANCE_FILE"

export const SEARCH_TRANSFER_VOUCHER = "SEARCH_TRANSFER_VOUCHER"

